### ISSUE TITLE
How to clone and build project on window

### ISSUE THREAD

**Issue by pubpy2015** [xiongziliang/ZLMediaPlayer#5]
Hi,

I am clone your project but can not build project on window:
![image](https://user-images.githubusercontent.com/59004953/84991126-49c01500-b170-11ea-8cb5-9ba4c8b9f1e4.png)

**Comment by xia-chu** [comment]
You need clone
https://github.com/xiongziliang/ZLToolKit/tree/1.0
and
https://github.com/xiongziliang/ZLMediaKit/tree/1.0

in the same root path of ZLMediaPlayer.

**Comment by pubpy2015** [comment]
ZLToolKit must in ZLMediaPlayer folder
![image](https://user-images.githubusercontent.com/59004953/85003261-2f8e3300-b180-11ea-80b8-3055c9b6fdbc.png)

but when builld, there are some error: 
![image](https://user-images.githubusercontent.com/59004953/85003474-7714bf00-b180-11ea-9920-03d31cc50742.png)

**Comment by xia-chu** [comment]
You must install SDL2

**Comment by xia-chu** [comment]
This project hasn't been maintained for a long time，you can refer this project:

https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_player.cpp

**Comment by pubpy2015** [comment]
Thanks,
